services:
  # --- VPN (Le tunnel sécurisé) ---
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_USER=A4DhMJcDg
      - OPENVPN_PASSWORD=01KMEC606GGD9Y16CYRRAS7XDQ
      - TZ=Europe/Paris
      - OPENVPN_CUSTOM_CONFIG=/gluetun/client.conf
      - DNS_ADDRESS=1.1.1.1 # DNS classiques
      - DOT=off # Désactive DNS-over-TLS (indispensable ici)
      - DNS_KEEP_NAMESERVER=on # Empêche Gluetun d'écraser le DNS
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24
    volumes:
      - ./docker-config/vpn:/gluetun
    ports:
      - 9091:9091 # Transmission Web UI
      - 8989:8989 # Sonarr
      - 7878:7878 # Radarr
      - 9696:9696 # Prowlarr
      - 6767:6767 # Bazarr
    restart: always

  # --- DOWNLOADER (Derrière le VPN) ---
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "container:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./docker-config/transmission:/config
      - ./data:/data
    depends_on:
      - vpn
    restart: always

  # --- INDEXEURS ---
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    network_mode: "container:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./docker-config/prowlarr:/config
    depends_on:
      - vpn
    restart: always

  # --- GESTIONNAIRES ---
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "container:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./docker-config/radarr:/config
      - ./data:/data
      - /media/raid/storage/Film:/data/media/old-movies # Ajoute ce lien
    depends_on:
      - vpn
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "container:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./docker-config/sonarr:/config
      - ./data:/data
    depends_on:
      - vpn
    restart: always

  jellyfin:
    image: jellyfin/jellyfin
    #ports:
    #- 8097:8096
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - ./docker-config/jellyfin/config:/config
      - ./docker-config/jellyfin/cache:/cache
      - type: bind
        source: ../
        target: /media
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # --- STATISTIQUES  ---
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ujc0tpw.ZQE6dbr8kwy
      - POSTGRES_DB=jellystat
    volumes:
      - ./docker-config/postgres:/var/lib/postgresql/data
    restart: always

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    ports:
      - 3001:3000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ujc0tpw.ZQE6dbr8kwy
      - POSTGRES_IP=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=jellystat
      - TZ=Europe/Paris
      - JWT_SECRET=dlkfjgblksjnclkjfdgndflkjgndflkjfnlkzgnerlkjgndkjn
    depends_on:
      - postgres
    restart: always
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ./docker-config/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  # --- HUB ---
  hub:
    build: ./hub
    container_name: synarr-hub
    environment:
      - BETTER_AUTH_SECRET=dlkfjgblksjnclkjfdgndflkjgndflkjfnlkzgnerlkjgndkjn
      - BETTER_AUTH_URL=http://localhost
      - DATABASE_PATH=/app/db/auth.db
    volumes:
      - ./docker-config/hub/db:/app/db
    restart: always

  # --- PROXY ---
  caddy:
    image: caddy:2-alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - hub
    restart: always

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: "container:vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./docker-config/bazarr:/config
      - ./data/media:/data/media # Accès à tes films pour écrire les .srt
      - /media/raid/storage/Film:/data/media/old-movies
      - /media/raid/storage/TVshows:/data/media/old-series
    depends_on:
      - vpn
    restart: always

volumes:
  caddy_data:
  caddy_config:

